<?php
/**
 * LineItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\fulfillment\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\fulfillment\ObjectSerializer;

/**
 * LineItem Class Doc Comment
 *
 * @category Class
 * @description This type contains the details of each line item in an order.
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LineItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'appliedPromotions' => '\macropage\SDKs\ebay\rest\fulfillment\Model\AppliedPromotion[]',
        'deliveryCost' => '\macropage\SDKs\ebay\rest\fulfillment\Model\DeliveryCost',
        'discountedLineItemCost' => '\macropage\SDKs\ebay\rest\fulfillment\Model\Amount',
        'ebayCollectAndRemitTaxes' => '\macropage\SDKs\ebay\rest\fulfillment\Model\EbayCollectAndRemitTax[]',
        'giftDetails' => '\macropage\SDKs\ebay\rest\fulfillment\Model\GiftDetails',
        'legacyItemId' => 'string',
        'legacyVariationId' => 'string',
        'lineItemCost' => '\macropage\SDKs\ebay\rest\fulfillment\Model\Amount',
        'lineItemFulfillmentInstructions' => '\macropage\SDKs\ebay\rest\fulfillment\Model\LineItemFulfillmentInstructions',
        'lineItemFulfillmentStatus' => 'string',
        'lineItemId' => 'string',
        'listingMarketplaceId' => 'string',
        'properties' => '\macropage\SDKs\ebay\rest\fulfillment\Model\LineItemProperties',
        'purchaseMarketplaceId' => 'string',
        'quantity' => 'int',
        'refunds' => '\macropage\SDKs\ebay\rest\fulfillment\Model\LineItemRefund[]',
        'sku' => 'string',
        'soldFormat' => 'string',
        'taxes' => '\macropage\SDKs\ebay\rest\fulfillment\Model\Tax[]',
        'title' => 'string',
        'total' => '\macropage\SDKs\ebay\rest\fulfillment\Model\Amount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'appliedPromotions' => null,
        'deliveryCost' => null,
        'discountedLineItemCost' => null,
        'ebayCollectAndRemitTaxes' => null,
        'giftDetails' => null,
        'legacyItemId' => null,
        'legacyVariationId' => null,
        'lineItemCost' => null,
        'lineItemFulfillmentInstructions' => null,
        'lineItemFulfillmentStatus' => null,
        'lineItemId' => null,
        'listingMarketplaceId' => null,
        'properties' => null,
        'purchaseMarketplaceId' => null,
        'quantity' => 'int32',
        'refunds' => null,
        'sku' => null,
        'soldFormat' => null,
        'taxes' => null,
        'title' => null,
        'total' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'appliedPromotions' => 'appliedPromotions',
        'deliveryCost' => 'deliveryCost',
        'discountedLineItemCost' => 'discountedLineItemCost',
        'ebayCollectAndRemitTaxes' => 'ebayCollectAndRemitTaxes',
        'giftDetails' => 'giftDetails',
        'legacyItemId' => 'legacyItemId',
        'legacyVariationId' => 'legacyVariationId',
        'lineItemCost' => 'lineItemCost',
        'lineItemFulfillmentInstructions' => 'lineItemFulfillmentInstructions',
        'lineItemFulfillmentStatus' => 'lineItemFulfillmentStatus',
        'lineItemId' => 'lineItemId',
        'listingMarketplaceId' => 'listingMarketplaceId',
        'properties' => 'properties',
        'purchaseMarketplaceId' => 'purchaseMarketplaceId',
        'quantity' => 'quantity',
        'refunds' => 'refunds',
        'sku' => 'sku',
        'soldFormat' => 'soldFormat',
        'taxes' => 'taxes',
        'title' => 'title',
        'total' => 'total'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'appliedPromotions' => 'setAppliedPromotions',
        'deliveryCost' => 'setDeliveryCost',
        'discountedLineItemCost' => 'setDiscountedLineItemCost',
        'ebayCollectAndRemitTaxes' => 'setEbayCollectAndRemitTaxes',
        'giftDetails' => 'setGiftDetails',
        'legacyItemId' => 'setLegacyItemId',
        'legacyVariationId' => 'setLegacyVariationId',
        'lineItemCost' => 'setLineItemCost',
        'lineItemFulfillmentInstructions' => 'setLineItemFulfillmentInstructions',
        'lineItemFulfillmentStatus' => 'setLineItemFulfillmentStatus',
        'lineItemId' => 'setLineItemId',
        'listingMarketplaceId' => 'setListingMarketplaceId',
        'properties' => 'setProperties',
        'purchaseMarketplaceId' => 'setPurchaseMarketplaceId',
        'quantity' => 'setQuantity',
        'refunds' => 'setRefunds',
        'sku' => 'setSku',
        'soldFormat' => 'setSoldFormat',
        'taxes' => 'setTaxes',
        'title' => 'setTitle',
        'total' => 'setTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'appliedPromotions' => 'getAppliedPromotions',
        'deliveryCost' => 'getDeliveryCost',
        'discountedLineItemCost' => 'getDiscountedLineItemCost',
        'ebayCollectAndRemitTaxes' => 'getEbayCollectAndRemitTaxes',
        'giftDetails' => 'getGiftDetails',
        'legacyItemId' => 'getLegacyItemId',
        'legacyVariationId' => 'getLegacyVariationId',
        'lineItemCost' => 'getLineItemCost',
        'lineItemFulfillmentInstructions' => 'getLineItemFulfillmentInstructions',
        'lineItemFulfillmentStatus' => 'getLineItemFulfillmentStatus',
        'lineItemId' => 'getLineItemId',
        'listingMarketplaceId' => 'getListingMarketplaceId',
        'properties' => 'getProperties',
        'purchaseMarketplaceId' => 'getPurchaseMarketplaceId',
        'quantity' => 'getQuantity',
        'refunds' => 'getRefunds',
        'sku' => 'getSku',
        'soldFormat' => 'getSoldFormat',
        'taxes' => 'getTaxes',
        'title' => 'getTitle',
        'total' => 'getTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['appliedPromotions'] = isset($data['appliedPromotions']) ? $data['appliedPromotions'] : null;
        $this->container['deliveryCost'] = isset($data['deliveryCost']) ? $data['deliveryCost'] : null;
        $this->container['discountedLineItemCost'] = isset($data['discountedLineItemCost']) ? $data['discountedLineItemCost'] : null;
        $this->container['ebayCollectAndRemitTaxes'] = isset($data['ebayCollectAndRemitTaxes']) ? $data['ebayCollectAndRemitTaxes'] : null;
        $this->container['giftDetails'] = isset($data['giftDetails']) ? $data['giftDetails'] : null;
        $this->container['legacyItemId'] = isset($data['legacyItemId']) ? $data['legacyItemId'] : null;
        $this->container['legacyVariationId'] = isset($data['legacyVariationId']) ? $data['legacyVariationId'] : null;
        $this->container['lineItemCost'] = isset($data['lineItemCost']) ? $data['lineItemCost'] : null;
        $this->container['lineItemFulfillmentInstructions'] = isset($data['lineItemFulfillmentInstructions']) ? $data['lineItemFulfillmentInstructions'] : null;
        $this->container['lineItemFulfillmentStatus'] = isset($data['lineItemFulfillmentStatus']) ? $data['lineItemFulfillmentStatus'] : null;
        $this->container['lineItemId'] = isset($data['lineItemId']) ? $data['lineItemId'] : null;
        $this->container['listingMarketplaceId'] = isset($data['listingMarketplaceId']) ? $data['listingMarketplaceId'] : null;
        $this->container['properties'] = isset($data['properties']) ? $data['properties'] : null;
        $this->container['purchaseMarketplaceId'] = isset($data['purchaseMarketplaceId']) ? $data['purchaseMarketplaceId'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['refunds'] = isset($data['refunds']) ? $data['refunds'] : null;
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['soldFormat'] = isset($data['soldFormat']) ? $data['soldFormat'] : null;
        $this->container['taxes'] = isset($data['taxes']) ? $data['taxes'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['total'] = isset($data['total']) ? $data['total'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets appliedPromotions
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\AppliedPromotion[]|null
     */
    public function getAppliedPromotions()
    {
        return $this->container['appliedPromotions'];
    }

    /**
     * Sets appliedPromotions
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\AppliedPromotion[]|null $appliedPromotions This array contains information about one or more sales promotions or discounts applied to the line item. It is always returned, but will be returned as an empty array if no special sales promotions or discounts apply to the order line item.
     *
     * @return $this
     */
    public function setAppliedPromotions($appliedPromotions)
    {
        $this->container['appliedPromotions'] = $appliedPromotions;

        return $this;
    }

    /**
     * Gets deliveryCost
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\DeliveryCost|null
     */
    public function getDeliveryCost()
    {
        return $this->container['deliveryCost'];
    }

    /**
     * Sets deliveryCost
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\DeliveryCost|null $deliveryCost deliveryCost
     *
     * @return $this
     */
    public function setDeliveryCost($deliveryCost)
    {
        $this->container['deliveryCost'] = $deliveryCost;

        return $this;
    }

    /**
     * Gets discountedLineItemCost
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null
     */
    public function getDiscountedLineItemCost()
    {
        return $this->container['discountedLineItemCost'];
    }

    /**
     * Sets discountedLineItemCost
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null $discountedLineItemCost discountedLineItemCost
     *
     * @return $this
     */
    public function setDiscountedLineItemCost($discountedLineItemCost)
    {
        $this->container['discountedLineItemCost'] = $discountedLineItemCost;

        return $this;
    }

    /**
     * Gets ebayCollectAndRemitTaxes
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\EbayCollectAndRemitTax[]|null
     */
    public function getEbayCollectAndRemitTaxes()
    {
        return $this->container['ebayCollectAndRemitTaxes'];
    }

    /**
     * Sets ebayCollectAndRemitTaxes
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\EbayCollectAndRemitTax[]|null $ebayCollectAndRemitTaxes This container will be returned if the order line item is subject to a 'Collect and Remit' tax that eBay will collect and remit to the proper taxing authority on the buyer's behalf. 'Collect and Remit' tax includes US state-mandated sales tax and 'Goods and Services' tax (collected in Australia and New Zealand). The amount of this tax is shown in the amount field, and the type of tax is shown in the taxType field. eBay will display the tax type and amount during checkout in accordance with the buyer's address, and handle collection and remittance of the tax without requiring the seller to take any action.
     *
     * @return $this
     */
    public function setEbayCollectAndRemitTaxes($ebayCollectAndRemitTaxes)
    {
        $this->container['ebayCollectAndRemitTaxes'] = $ebayCollectAndRemitTaxes;

        return $this;
    }

    /**
     * Gets giftDetails
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\GiftDetails|null
     */
    public function getGiftDetails()
    {
        return $this->container['giftDetails'];
    }

    /**
     * Sets giftDetails
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\GiftDetails|null $giftDetails giftDetails
     *
     * @return $this
     */
    public function setGiftDetails($giftDetails)
    {
        $this->container['giftDetails'] = $giftDetails;

        return $this;
    }

    /**
     * Gets legacyItemId
     *
     * @return string|null
     */
    public function getLegacyItemId()
    {
        return $this->container['legacyItemId'];
    }

    /**
     * Sets legacyItemId
     *
     * @param string|null $legacyItemId The eBay-generated legacy listing item ID of the listing. Note that the unique identifier of a listing in REST-based APIs is called the listingId instead.
     *
     * @return $this
     */
    public function setLegacyItemId($legacyItemId)
    {
        $this->container['legacyItemId'] = $legacyItemId;

        return $this;
    }

    /**
     * Gets legacyVariationId
     *
     * @return string|null
     */
    public function getLegacyVariationId()
    {
        return $this->container['legacyVariationId'];
    }

    /**
     * Sets legacyVariationId
     *
     * @param string|null $legacyVariationId The unique identifier of a single variation within a multiple-variation listing. This field is only returned if the line item purchased was from a multiple-variation listing.
     *
     * @return $this
     */
    public function setLegacyVariationId($legacyVariationId)
    {
        $this->container['legacyVariationId'] = $legacyVariationId;

        return $this;
    }

    /**
     * Gets lineItemCost
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null
     */
    public function getLineItemCost()
    {
        return $this->container['lineItemCost'];
    }

    /**
     * Sets lineItemCost
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null $lineItemCost lineItemCost
     *
     * @return $this
     */
    public function setLineItemCost($lineItemCost)
    {
        $this->container['lineItemCost'] = $lineItemCost;

        return $this;
    }

    /**
     * Gets lineItemFulfillmentInstructions
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemFulfillmentInstructions|null
     */
    public function getLineItemFulfillmentInstructions()
    {
        return $this->container['lineItemFulfillmentInstructions'];
    }

    /**
     * Sets lineItemFulfillmentInstructions
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemFulfillmentInstructions|null $lineItemFulfillmentInstructions lineItemFulfillmentInstructions
     *
     * @return $this
     */
    public function setLineItemFulfillmentInstructions($lineItemFulfillmentInstructions)
    {
        $this->container['lineItemFulfillmentInstructions'] = $lineItemFulfillmentInstructions;

        return $this;
    }

    /**
     * Gets lineItemFulfillmentStatus
     *
     * @return string|null
     */
    public function getLineItemFulfillmentStatus()
    {
        return $this->container['lineItemFulfillmentStatus'];
    }

    /**
     * Sets lineItemFulfillmentStatus
     *
     * @param string|null $lineItemFulfillmentStatus This enumeration value indicates the current fulfillment status of the line item. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/LineItemFulfillmentStatusEnum.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setLineItemFulfillmentStatus($lineItemFulfillmentStatus)
    {
        $this->container['lineItemFulfillmentStatus'] = $lineItemFulfillmentStatus;

        return $this;
    }

    /**
     * Gets lineItemId
     *
     * @return string|null
     */
    public function getLineItemId()
    {
        return $this->container['lineItemId'];
    }

    /**
     * Sets lineItemId
     *
     * @param string|null $lineItemId This is the unique identifier of an eBay order line item. This field is created as soon as there is a commitment to buy from the seller.
     *
     * @return $this
     */
    public function setLineItemId($lineItemId)
    {
        $this->container['lineItemId'] = $lineItemId;

        return $this;
    }

    /**
     * Gets listingMarketplaceId
     *
     * @return string|null
     */
    public function getListingMarketplaceId()
    {
        return $this->container['listingMarketplaceId'];
    }

    /**
     * Sets listingMarketplaceId
     *
     * @param string|null $listingMarketplaceId The unique identifier of the eBay marketplace where the line item was listed. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/MarketplaceIdEnum.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setListingMarketplaceId($listingMarketplaceId)
    {
        $this->container['listingMarketplaceId'] = $listingMarketplaceId;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemProperties|null
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemProperties|null $properties properties
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->container['properties'] = $properties;

        return $this;
    }

    /**
     * Gets purchaseMarketplaceId
     *
     * @return string|null
     */
    public function getPurchaseMarketplaceId()
    {
        return $this->container['purchaseMarketplaceId'];
    }

    /**
     * Sets purchaseMarketplaceId
     *
     * @param string|null $purchaseMarketplaceId The unique identifier of the eBay marketplace where the line item was listed. Often, the listingMarketplaceId and the purchaseMarketplaceId identifier are the same, but there are occasions when an item will surface on multiple eBay marketplaces. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/MarketplaceIdEnum.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setPurchaseMarketplaceId($purchaseMarketplaceId)
    {
        $this->container['purchaseMarketplaceId'] = $purchaseMarketplaceId;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int|null $quantity The number of units of the line item in the order. These are represented as a group by a single lineItemId.
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets refunds
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemRefund[]|null
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\LineItemRefund[]|null $refunds This array is always returned, but is returned as an empty array unless the seller has submitted a partial or full refund to the buyer for the order. If a refund has occurred, the refund amount and refund date will be shown for each refund.
     *
     * @return $this
     */
    public function setRefunds($refunds)
    {
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku Seller-defined Stock-Keeping Unit (SKU). This inventory identifier must be unique within the seller's eBay inventory. SKUs are optional when listing in the legacy/Trading API system, but SKUs are required when listing items through the Inventory API model.
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets soldFormat
     *
     * @return string|null
     */
    public function getSoldFormat()
    {
        return $this->container['soldFormat'];
    }

    /**
     * Sets soldFormat
     *
     * @param string|null $soldFormat The eBay listing type of the line item. The most common listing types are AUCTION and FIXED_PRICE. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/SoldFormatEnum.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setSoldFormat($soldFormat)
    {
        $this->container['soldFormat'] = $soldFormat;

        return $this;
    }

    /**
     * Gets taxes
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\Tax[]|null
     */
    public function getTaxes()
    {
        return $this->container['taxes'];
    }

    /**
     * Sets taxes
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\Tax[]|null $taxes Contains a list of taxes applied to the line item, if any. This array is always returned, but will be returned as empty if no taxes are applicable to the line item, or if only eBay 'Collect and Remit' tax is applicable.
     *
     * @return $this
     */
    public function setTaxes($taxes)
    {
        $this->container['taxes'] = $taxes;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The title of the listing.
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets total
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\Amount|null $total total
     *
     * @return $this
     */
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


