<?php
/**
 * Order
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\fulfillment\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\fulfillment\ObjectSerializer;

/**
 * Order Class Doc Comment
 *
 * @category Class
 * @description This type contains the details of an order, including information about the buyer, order history, shipping fulfillments, line items, costs, payments, and order fulfillment status.
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Order implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'buyer' => '\macropage\SDKs\ebay\rest\fulfillment\Model\Buyer',
        'buyerCheckoutNotes' => 'string',
        'cancelStatus' => '\macropage\SDKs\ebay\rest\fulfillment\Model\CancelStatus',
        'creationDate' => 'string',
        'ebayCollectAndRemitTax' => 'bool',
        'fulfillmentHrefs' => 'string[]',
        'fulfillmentStartInstructions' => '\macropage\SDKs\ebay\rest\fulfillment\Model\FulfillmentStartInstruction[]',
        'lastModifiedDate' => 'string',
        'legacyOrderId' => 'string',
        'lineItems' => '\macropage\SDKs\ebay\rest\fulfillment\Model\LineItem[]',
        'orderFulfillmentStatus' => 'string',
        'orderId' => 'string',
        'orderPaymentStatus' => 'string',
        'paymentSummary' => '\macropage\SDKs\ebay\rest\fulfillment\Model\PaymentSummary',
        'pricingSummary' => '\macropage\SDKs\ebay\rest\fulfillment\Model\PricingSummary',
        'salesRecordReference' => 'string',
        'sellerId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'buyer' => null,
        'buyerCheckoutNotes' => null,
        'cancelStatus' => null,
        'creationDate' => null,
        'ebayCollectAndRemitTax' => null,
        'fulfillmentHrefs' => null,
        'fulfillmentStartInstructions' => null,
        'lastModifiedDate' => null,
        'legacyOrderId' => null,
        'lineItems' => null,
        'orderFulfillmentStatus' => null,
        'orderId' => null,
        'orderPaymentStatus' => null,
        'paymentSummary' => null,
        'pricingSummary' => null,
        'salesRecordReference' => null,
        'sellerId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buyer' => 'buyer',
        'buyerCheckoutNotes' => 'buyerCheckoutNotes',
        'cancelStatus' => 'cancelStatus',
        'creationDate' => 'creationDate',
        'ebayCollectAndRemitTax' => 'ebayCollectAndRemitTax',
        'fulfillmentHrefs' => 'fulfillmentHrefs',
        'fulfillmentStartInstructions' => 'fulfillmentStartInstructions',
        'lastModifiedDate' => 'lastModifiedDate',
        'legacyOrderId' => 'legacyOrderId',
        'lineItems' => 'lineItems',
        'orderFulfillmentStatus' => 'orderFulfillmentStatus',
        'orderId' => 'orderId',
        'orderPaymentStatus' => 'orderPaymentStatus',
        'paymentSummary' => 'paymentSummary',
        'pricingSummary' => 'pricingSummary',
        'salesRecordReference' => 'salesRecordReference',
        'sellerId' => 'sellerId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buyer' => 'setBuyer',
        'buyerCheckoutNotes' => 'setBuyerCheckoutNotes',
        'cancelStatus' => 'setCancelStatus',
        'creationDate' => 'setCreationDate',
        'ebayCollectAndRemitTax' => 'setEbayCollectAndRemitTax',
        'fulfillmentHrefs' => 'setFulfillmentHrefs',
        'fulfillmentStartInstructions' => 'setFulfillmentStartInstructions',
        'lastModifiedDate' => 'setLastModifiedDate',
        'legacyOrderId' => 'setLegacyOrderId',
        'lineItems' => 'setLineItems',
        'orderFulfillmentStatus' => 'setOrderFulfillmentStatus',
        'orderId' => 'setOrderId',
        'orderPaymentStatus' => 'setOrderPaymentStatus',
        'paymentSummary' => 'setPaymentSummary',
        'pricingSummary' => 'setPricingSummary',
        'salesRecordReference' => 'setSalesRecordReference',
        'sellerId' => 'setSellerId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buyer' => 'getBuyer',
        'buyerCheckoutNotes' => 'getBuyerCheckoutNotes',
        'cancelStatus' => 'getCancelStatus',
        'creationDate' => 'getCreationDate',
        'ebayCollectAndRemitTax' => 'getEbayCollectAndRemitTax',
        'fulfillmentHrefs' => 'getFulfillmentHrefs',
        'fulfillmentStartInstructions' => 'getFulfillmentStartInstructions',
        'lastModifiedDate' => 'getLastModifiedDate',
        'legacyOrderId' => 'getLegacyOrderId',
        'lineItems' => 'getLineItems',
        'orderFulfillmentStatus' => 'getOrderFulfillmentStatus',
        'orderId' => 'getOrderId',
        'orderPaymentStatus' => 'getOrderPaymentStatus',
        'paymentSummary' => 'getPaymentSummary',
        'pricingSummary' => 'getPricingSummary',
        'salesRecordReference' => 'getSalesRecordReference',
        'sellerId' => 'getSellerId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buyer'] = isset($data['buyer']) ? $data['buyer'] : null;
        $this->container['buyerCheckoutNotes'] = isset($data['buyerCheckoutNotes']) ? $data['buyerCheckoutNotes'] : null;
        $this->container['cancelStatus'] = isset($data['cancelStatus']) ? $data['cancelStatus'] : null;
        $this->container['creationDate'] = isset($data['creationDate']) ? $data['creationDate'] : null;
        $this->container['ebayCollectAndRemitTax'] = isset($data['ebayCollectAndRemitTax']) ? $data['ebayCollectAndRemitTax'] : null;
        $this->container['fulfillmentHrefs'] = isset($data['fulfillmentHrefs']) ? $data['fulfillmentHrefs'] : null;
        $this->container['fulfillmentStartInstructions'] = isset($data['fulfillmentStartInstructions']) ? $data['fulfillmentStartInstructions'] : null;
        $this->container['lastModifiedDate'] = isset($data['lastModifiedDate']) ? $data['lastModifiedDate'] : null;
        $this->container['legacyOrderId'] = isset($data['legacyOrderId']) ? $data['legacyOrderId'] : null;
        $this->container['lineItems'] = isset($data['lineItems']) ? $data['lineItems'] : null;
        $this->container['orderFulfillmentStatus'] = isset($data['orderFulfillmentStatus']) ? $data['orderFulfillmentStatus'] : null;
        $this->container['orderId'] = isset($data['orderId']) ? $data['orderId'] : null;
        $this->container['orderPaymentStatus'] = isset($data['orderPaymentStatus']) ? $data['orderPaymentStatus'] : null;
        $this->container['paymentSummary'] = isset($data['paymentSummary']) ? $data['paymentSummary'] : null;
        $this->container['pricingSummary'] = isset($data['pricingSummary']) ? $data['pricingSummary'] : null;
        $this->container['salesRecordReference'] = isset($data['salesRecordReference']) ? $data['salesRecordReference'] : null;
        $this->container['sellerId'] = isset($data['sellerId']) ? $data['sellerId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buyer
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\Buyer|null
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\Buyer|null $buyer buyer
     *
     * @return $this
     */
    public function setBuyer($buyer)
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets buyerCheckoutNotes
     *
     * @return string|null
     */
    public function getBuyerCheckoutNotes()
    {
        return $this->container['buyerCheckoutNotes'];
    }

    /**
     * Sets buyerCheckoutNotes
     *
     * @param string|null $buyerCheckoutNotes This field contains any comments that the buyer left for the seller about the order during checkout process. This field is only returned if a buyer left comments at checkout time.
     *
     * @return $this
     */
    public function setBuyerCheckoutNotes($buyerCheckoutNotes)
    {
        $this->container['buyerCheckoutNotes'] = $buyerCheckoutNotes;

        return $this;
    }

    /**
     * Gets cancelStatus
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\CancelStatus|null
     */
    public function getCancelStatus()
    {
        return $this->container['cancelStatus'];
    }

    /**
     * Sets cancelStatus
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\CancelStatus|null $cancelStatus cancelStatus
     *
     * @return $this
     */
    public function setCancelStatus($cancelStatus)
    {
        $this->container['cancelStatus'] = $cancelStatus;

        return $this;
    }

    /**
     * Gets creationDate
     *
     * @return string|null
     */
    public function getCreationDate()
    {
        return $this->container['creationDate'];
    }

    /**
     * Sets creationDate
     *
     * @param string|null $creationDate The date and time that the order was created. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. Format: YYYY-MM-DDTHH:MM:SS.SSSZ Example: 2015-08-04T19:09:02.768Z
     *
     * @return $this
     */
    public function setCreationDate($creationDate)
    {
        $this->container['creationDate'] = $creationDate;

        return $this;
    }

    /**
     * Gets ebayCollectAndRemitTax
     *
     * @return bool|null
     */
    public function getEbayCollectAndRemitTax()
    {
        return $this->container['ebayCollectAndRemitTax'];
    }

    /**
     * Sets ebayCollectAndRemitTax
     *
     * @param bool|null $ebayCollectAndRemitTax This field is only returned if true, and indicates that eBay will collect tax (US state-mandates sales tax or 'goods and services' tax in Australia or New Zealand) for at least one line item in the order, and remit the tax to the taxing authority of the buyer's residence. If this field is returned, the seller should search for one or more ebayCollectAndRemitTaxes containers at the line item level to get more information about the type of tax and the amount.
     *
     * @return $this
     */
    public function setEbayCollectAndRemitTax($ebayCollectAndRemitTax)
    {
        $this->container['ebayCollectAndRemitTax'] = $ebayCollectAndRemitTax;

        return $this;
    }

    /**
     * Gets fulfillmentHrefs
     *
     * @return string[]|null
     */
    public function getFulfillmentHrefs()
    {
        return $this->container['fulfillmentHrefs'];
    }

    /**
     * Sets fulfillmentHrefs
     *
     * @param string[]|null $fulfillmentHrefs This array contains a list of one or more getShippingFulfillment call URIs that can be used to retrieve shipping fulfillments that have been set up for the order.
     *
     * @return $this
     */
    public function setFulfillmentHrefs($fulfillmentHrefs)
    {
        $this->container['fulfillmentHrefs'] = $fulfillmentHrefs;

        return $this;
    }

    /**
     * Gets fulfillmentStartInstructions
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\FulfillmentStartInstruction[]|null
     */
    public function getFulfillmentStartInstructions()
    {
        return $this->container['fulfillmentStartInstructions'];
    }

    /**
     * Sets fulfillmentStartInstructions
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\FulfillmentStartInstruction[]|null $fulfillmentStartInstructions This container consists of a set of specifications for fulfilling the order, including the type of fulfillment, shipping carrier and service, shipping address, and estimated delivery window. These instructions are derived from the buyer's and seller's eBay account preferences, the listing parameters, and the buyer's checkout selections. The seller can use them as a starting point for packaging, addressing, and shipping the order. Note: Although this container is presented as an array, it currently returns only one set of fulfillment specifications. Additional array members will be supported in future functionality.
     *
     * @return $this
     */
    public function setFulfillmentStartInstructions($fulfillmentStartInstructions)
    {
        $this->container['fulfillmentStartInstructions'] = $fulfillmentStartInstructions;

        return $this;
    }

    /**
     * Gets lastModifiedDate
     *
     * @return string|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['lastModifiedDate'];
    }

    /**
     * Sets lastModifiedDate
     *
     * @param string|null $lastModifiedDate The date and time that the order was last modified. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. Format: YYYY-MM-DDTHH:MM:SS.SSSZ Example: 2015-08-04T19:09:02.768Z
     *
     * @return $this
     */
    public function setLastModifiedDate($lastModifiedDate)
    {
        $this->container['lastModifiedDate'] = $lastModifiedDate;

        return $this;
    }

    /**
     * Gets legacyOrderId
     *
     * @return string|null
     */
    public function getLegacyOrderId()
    {
        return $this->container['legacyOrderId'];
    }

    /**
     * Sets legacyOrderId
     *
     * @param string|null $legacyOrderId The unique identifier of the order in legacy format, as traditionally used by the Trading API (and other legacy APIs). Both the orderId field and this field are always returned. Note: In June 2019, Order IDs in REST APIs transitioned to a new format. For the Trading and other legacy APIs, by using version control/compatibility level, users have the option of using the older legacy order ID format, or they can migrate to the new order ID format, which is the same order ID format being used by REST APIs. Although users of the Trading API (and other legacy APIs) can now transition to the new order ID format, this legacyOrderId field will still return order IDs in the old format to distinguish between the old and new order IDs.
     *
     * @return $this
     */
    public function setLegacyOrderId($legacyOrderId)
    {
        $this->container['legacyOrderId'] = $legacyOrderId;

        return $this;
    }

    /**
     * Gets lineItems
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\LineItem[]|null
     */
    public function getLineItems()
    {
        return $this->container['lineItems'];
    }

    /**
     * Sets lineItems
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\LineItem[]|null $lineItems This array contains the details for all line items that comprise the order.
     *
     * @return $this
     */
    public function setLineItems($lineItems)
    {
        $this->container['lineItems'] = $lineItems;

        return $this;
    }

    /**
     * Gets orderFulfillmentStatus
     *
     * @return string|null
     */
    public function getOrderFulfillmentStatus()
    {
        return $this->container['orderFulfillmentStatus'];
    }

    /**
     * Sets orderFulfillmentStatus
     *
     * @param string|null $orderFulfillmentStatus The degree to which fulfillment of the order is complete. See the OrderFulfillmentStatus type definition for more information about each possible fulfillment state. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/OrderFulfillmentStatus.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setOrderFulfillmentStatus($orderFulfillmentStatus)
    {
        $this->container['orderFulfillmentStatus'] = $orderFulfillmentStatus;

        return $this;
    }

    /**
     * Gets orderId
     *
     * @return string|null
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId
     *
     * @param string|null $orderId The unique identifier of the order. Both the legacyOrderId field (traditionally used by Trading and other legacy APIS) and this field are always returned. Note: In June 2019, Order IDs in REST APIs transitioned to a new format. For the Trading and other legacy APIs, by using version control/compatibility level, users have the option of using the older legacy order ID format, or they can migrate to the new order ID format, which is the same order ID format being used by REST APIs. The new format is a non-parsable string, globally unique across all eBay marketplaces, and consistent for both single line item and multiple line item orders. These order identifiers are automatically generated after buyer payment, and unlike in the past, instead of just being known and exposed to the seller, these unique order identifiers will also be known and used/referenced by the buyer and eBay customer support.
     *
     * @return $this
     */
    public function setOrderId($orderId)
    {
        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets orderPaymentStatus
     *
     * @return string|null
     */
    public function getOrderPaymentStatus()
    {
        return $this->container['orderPaymentStatus'];
    }

    /**
     * Sets orderPaymentStatus
     *
     * @param string|null $orderPaymentStatus The enumeration value returned in this field indicates the current payment status of an order, or in case of a refund request, the current status of the refund. See the OrderPaymentStatusEnum type definition for more information about each possible payment/refund state. For implementation help, refer to <a href='https://developer.ebay.com/devzone/rest/api-ref/fulfillment/types/OrderPaymentStatusEnum.html'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setOrderPaymentStatus($orderPaymentStatus)
    {
        $this->container['orderPaymentStatus'] = $orderPaymentStatus;

        return $this;
    }

    /**
     * Gets paymentSummary
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\PaymentSummary|null
     */
    public function getPaymentSummary()
    {
        return $this->container['paymentSummary'];
    }

    /**
     * Sets paymentSummary
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\PaymentSummary|null $paymentSummary paymentSummary
     *
     * @return $this
     */
    public function setPaymentSummary($paymentSummary)
    {
        $this->container['paymentSummary'] = $paymentSummary;

        return $this;
    }

    /**
     * Gets pricingSummary
     *
     * @return \macropage\SDKs\ebay\rest\fulfillment\Model\PricingSummary|null
     */
    public function getPricingSummary()
    {
        return $this->container['pricingSummary'];
    }

    /**
     * Sets pricingSummary
     *
     * @param \macropage\SDKs\ebay\rest\fulfillment\Model\PricingSummary|null $pricingSummary pricingSummary
     *
     * @return $this
     */
    public function setPricingSummary($pricingSummary)
    {
        $this->container['pricingSummary'] = $pricingSummary;

        return $this;
    }

    /**
     * Gets salesRecordReference
     *
     * @return string|null
     */
    public function getSalesRecordReference()
    {
        return $this->container['salesRecordReference'];
    }

    /**
     * Sets salesRecordReference
     *
     * @param string|null $salesRecordReference An eBay-generated identifier that is used to identify and manage orders through the Selling Manager and Selling Manager Pro tools. This order identifier can also be found on the Orders grid page and in the Sales Record pages in Seller Hub. A salesRecordReference number is only generated and returned at the order level, and not at the order line item level. In cases where the seller does not have a Selling Manager or Selling Manager Pro subscription nor access to Seller Hub, this field may not be returned.
     *
     * @return $this
     */
    public function setSalesRecordReference($salesRecordReference)
    {
        $this->container['salesRecordReference'] = $salesRecordReference;

        return $this;
    }

    /**
     * Gets sellerId
     *
     * @return string|null
     */
    public function getSellerId()
    {
        return $this->container['sellerId'];
    }

    /**
     * Sets sellerId
     *
     * @param string|null $sellerId The unique eBay user ID of the seller who sold the order.
     *
     * @return $this
     */
    public function setSellerId($sellerId)
    {
        $this->container['sellerId'] = $sellerId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


