<?php
/**
 * DeliveryCostTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

use PHPUnit\Framework\TestCase;

/**
 * DeliveryCostTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains a breakdown of all costs associated with the fulfillment of a line item.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeliveryCostTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DeliveryCost"
     */
    public function testDeliveryCost()
    {
    }

    /**
     * Test attribute "importCharges"
     */
    public function testPropertyImportCharges()
    {
    }

    /**
     * Test attribute "shippingCost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "shippingIntermediationFee"
     */
    public function testPropertyShippingIntermediationFee()
    {
    }
}
