<?php
/**
 * ErrorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

/**
 * ErrorTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains a error or warning related to a call request.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Error"
     */
    public function testError()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "errorId"
     */
    public function testPropertyErrorId()
    {
    }

    /**
     * Test attribute "inputRefIds"
     */
    public function testPropertyInputRefIds()
    {
    }

    /**
     * Test attribute "longMessage"
     */
    public function testPropertyLongMessage()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "outputRefIds"
     */
    public function testPropertyOutputRefIds()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "subdomain"
     */
    public function testPropertySubdomain()
    {
    }
}
