<?php
/**
 * FulfillmentStartInstructionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

use PHPUnit\Framework\TestCase;

/**
 * FulfillmentStartInstructionTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains a set of specifications for processing a fulfillment of an order, including the type of fulfillment, shipping carrier and service, addressing details, and estimated delivery window. These instructions are derived from the buyer&#39;s and seller&#39;s eBay account preferences, the listing parameters, and the buyer&#39;s checkout selections. The seller can use them as a starting point for packaging, addressing, and shipping the order.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FulfillmentStartInstructionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FulfillmentStartInstruction"
     */
    public function testFulfillmentStartInstruction()
    {
    }

    /**
     * Test attribute "ebaySupportedFulfillment"
     */
    public function testPropertyEbaySupportedFulfillment()
    {
    }

    /**
     * Test attribute "finalDestinationAddress"
     */
    public function testPropertyFinalDestinationAddress()
    {
    }

    /**
     * Test attribute "fulfillmentInstructionsType"
     */
    public function testPropertyFulfillmentInstructionsType()
    {
    }

    /**
     * Test attribute "maxEstimatedDeliveryDate"
     */
    public function testPropertyMaxEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "minEstimatedDeliveryDate"
     */
    public function testPropertyMinEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "pickupStep"
     */
    public function testPropertyPickupStep()
    {
    }

    /**
     * Test attribute "shippingStep"
     */
    public function testPropertyShippingStep()
    {
    }
}
