<?php
/**
 * LineItemFulfillmentInstructionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

/**
 * LineItemFulfillmentInstructionsTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the specifications for processing the fulfillment of a line item, including the handling window and the delivery window. These fields provide guidance for eBay Guaranteed Delivery as well as for non-guaranteed delivery.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LineItemFulfillmentInstructionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LineItemFulfillmentInstructions"
     */
    public function testLineItemFulfillmentInstructions()
    {
    }

    /**
     * Test attribute "guaranteedDelivery"
     */
    public function testPropertyGuaranteedDelivery()
    {
    }

    /**
     * Test attribute "maxEstimatedDeliveryDate"
     */
    public function testPropertyMaxEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "minEstimatedDeliveryDate"
     */
    public function testPropertyMinEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "shipByDate"
     */
    public function testPropertyShipByDate()
    {
    }
}
