<?php
/**
 * PaymentDisputeSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

/**
 * PaymentDisputeSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by each payment dispute that is returned with the getPaymentDisputeSummaries method.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentDisputeSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentDisputeSummary"
     */
    public function testPaymentDisputeSummary()
    {
    }

    /**
     * Test attribute "paymentDisputeId"
     */
    public function testPropertyPaymentDisputeId()
    {
    }

    /**
     * Test attribute "paymentDisputeStatus"
     */
    public function testPropertyPaymentDisputeStatus()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "openDate"
     */
    public function testPropertyOpenDate()
    {
    }

    /**
     * Test attribute "closedDate"
     */
    public function testPropertyClosedDate()
    {
    }

    /**
     * Test attribute "respondByDate"
     */
    public function testPropertyRespondByDate()
    {
    }

    /**
     * Test attribute "buyerUsername"
     */
    public function testPropertyBuyerUsername()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }
}
