<?php
/**
 * PaymentHoldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

/**
 * PaymentHoldTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about a hold placed on a payment to a seller for an order, including the reason why the buyer&#39;s payment for the order is being held, the expected release date of the funds into the seller&#39;s account, the current state of the hold, and the actual release date if the payment has been released, and possible actions the seller can take to expedite the payout of funds into their account.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentHoldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentHold"
     */
    public function testPaymentHold()
    {
    }

    /**
     * Test attribute "expectedReleaseDate"
     */
    public function testPropertyExpectedReleaseDate()
    {
    }

    /**
     * Test attribute "holdAmount"
     */
    public function testPropertyHoldAmount()
    {
    }

    /**
     * Test attribute "holdReason"
     */
    public function testPropertyHoldReason()
    {
    }

    /**
     * Test attribute "holdState"
     */
    public function testPropertyHoldState()
    {
    }

    /**
     * Test attribute "releaseDate"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "sellerActionsToRelease"
     */
    public function testPropertySellerActionsToRelease()
    {
    }
}
