<?php
/**
 * PaymentDisputeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the base response of the getPaymentDispute method. The getPaymentDispute method retrieves detailed information on a specific payment dispute.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentDisputeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentDispute"
     */
    public function testPaymentDispute()
    {
    }

    /**
     * Test attribute "paymentDisputeId"
     */
    public function testPropertyPaymentDisputeId()
    {
    }

    /**
     * Test attribute "paymentDisputeStatus"
     */
    public function testPropertyPaymentDisputeStatus()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "openDate"
     */
    public function testPropertyOpenDate()
    {
    }

    /**
     * Test attribute "closedDate"
     */
    public function testPropertyClosedDate()
    {
    }

    /**
     * Test attribute "respondByDate"
     */
    public function testPropertyRespondByDate()
    {
    }

    /**
     * Test attribute "lineItems"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {
    }

    /**
     * Test attribute "returnAddress"
     */
    public function testPropertyReturnAddress()
    {
    }

    /**
     * Test attribute "sellerResponse"
     */
    public function testPropertySellerResponse()
    {
    }

    /**
     * Test attribute "availableChoices"
     */
    public function testPropertyAvailableChoices()
    {
    }

    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
    }

    /**
     * Test attribute "evidence"
     */
    public function testPropertyEvidence()
    {
    }

    /**
     * Test attribute "evidenceRequests"
     */
    public function testPropertyEvidenceRequests()
    {
    }

    /**
     * Test attribute "buyerProvided"
     */
    public function testPropertyBuyerProvided()
    {
    }

    /**
     * Test attribute "buyerUsername"
     */
    public function testPropertyBuyerUsername()
    {
    }
}
