<?php
/**
 * ShippingFulfillmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

/**
 * ShippingFulfillmentTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the complete details of an existing fulfillment for an order.
 * @package     macropage\SDKs\ebay\rest\fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingFulfillmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingFulfillment"
     */
    public function testShippingFulfillment()
    {
    }

    /**
     * Test attribute "fulfillmentId"
     */
    public function testPropertyFulfillmentId()
    {
    }

    /**
     * Test attribute "lineItems"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "shipmentTrackingNumber"
     */
    public function testPropertyShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "shippedDate"
     */
    public function testPropertyShippedDate()
    {
    }

    /**
     * Test attribute "shippingCarrierCode"
     */
    public function testPropertyShippingCarrierCode()
    {
    }
}
