<?php
/**
 * PaymentDisputeApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

use \macropage\SDKs\ebay\rest\fulfillment\Configuration;
use \macropage\SDKs\ebay\rest\fulfillment\ApiException;
use \macropage\SDKs\ebay\rest\fulfillment\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeApiTest Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentDisputeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fetchEvidenceContent
     *
     * Get Payment Dispute Evidence File.
     *
     */
    public function testFetchEvidenceContent()
    {
    }

    /**
     * Test case for getActivities
     *
     * Get Payment Dispute Activity.
     *
     */
    public function testGetActivities()
    {
    }

    /**
     * Test case for getPaymentDispute
     *
     * Get Payment Dispute Details.
     *
     */
    public function testGetPaymentDispute()
    {
    }

    /**
     * Test case for getPaymentDisputeSummaries
     *
     * Search Payment Dispute by Filters.
     *
     */
    public function testGetPaymentDisputeSummaries()
    {
    }
}
