<?php
/**
 * ShippingFulfillmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: 1.11.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace macropage\SDKs\ebay\rest\fulfillment;

use \macropage\SDKs\ebay\rest\fulfillment\Configuration;
use \macropage\SDKs\ebay\rest\fulfillment\ApiException;
use \macropage\SDKs\ebay\rest\fulfillment\ObjectSerializer;

/**
 * ShippingFulfillmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingFulfillmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createShippingFulfillment
     *
     * Create a Shipping Fulfillment.
     *
     */
    public function testCreateShippingFulfillment()
    {
    }

    /**
     * Test case for getShippingFulfillment
     *
     * Get a Shipping Fulfillment.
     *
     */
    public function testGetShippingFulfillment()
    {
    }

    /**
     * Test case for getShippingFulfillments
     *
     * Get Shipping Fulfillments.
     *
     */
    public function testGetShippingFulfillments()
    {
    }
}
